### ISSUE TITLE
MVP 1: User Auth

### ISSUE THREAD

**Issue by fmbf** [fmbf/spotify_clone#1]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by ajansel** [comment]
Excellent work so far, nicely done! I have provided some feedback below, let me know if you have any questions. 

General Feedback 
- [ ] Currently, when I navigate to something random like `https://spotifyx.herokuapp.com/#/hjkgmhhgmghh` it renders the root because it is the last route in your switch, but really it should be an auth/protected route that truly redirect them to the root. Thus, it renders the root AND changes the path to: `https://spotifyx.herokuapp.com/#`

Homepage 
- [ ] This is looking pretty good! How would you feel about changing the background color. It feels a little too plain with it being a splash page, especially to a recruiter. I took a screenshot of spotify's background when logging in. This might be something cool to do as a background and your pictures / buttons would look nice on top of it. 
![image](https://user-images.githubusercontent.com/29723340/35697182-4a42c1f0-073e-11e8-9dfc-51743928bd9d.png)

- [x] The font for your buttons seems a little thin. Maybe try making them bold and see if you like that more? 
- [ ] The buttons also need to have cursor: pointer on hover 

Login / Sign up pages
- [ ] I have the same feedback about the background with the session forms. I think something like the black background with a design of some sort (similar to the picture above how Spotify actually does it) would be ideal 
- [ ] All of the buttons should have cursor: pointer on hover as well as your 'Log In' / `Sign Up` buttons that toggle between the two pages and your logo that links to your splash page (basically everything the user can click on should switch to a pointer so that it is clear they can click) 
- [x] The 'signup' and 'login' headers at the top of your form should be larger
- [x] When I click on 'DEMO USER' from either page, it seems it is redirecting to the splash page before taking me to the resulting page, but should instead redirect me straight to the resulting page

**Comment by fmbf** [comment]
Hi AJ!

Thanks for the notes, great ideas! 
I’m wondering what the best format to save/complete feedback is. Could you email me the actual MD file? I think that way I can check off the boxes as I go and keep everything in atom as Tabs.
Thanks!

**Comment by ajansel** [comment]
Looks great!
